version: 1.0.{build}
image: Visual Studio 2022

branches:
  only:
    - master

install:
  - nuget restore BadBlocksPlaceholder.sln

build:
  project: BadBlocksPlaceholder.sln
  verbosity: minimal

configuration: Release
